#!/usr/bin/env bash

icons=("" "" "")
brightness=$(brightnessctl i | sed -En 's/.*\(([0-9]+)%\).*/\1/p')

# initial
icon=${icons[$(awk -v n="${brightness}" 'BEGIN{print int(n/34)}')]}
echo '{ "level": '"${brightness}"', "icon": "'"$icon"'" }'

udevadm monitor | rg --line-buffered "backlight" | while read -r _; do
  icon="${icons[$(awk -v n="{brightness}" 'BEGIN{print int(n/34)}')]}"

  echo '{ "level": '"$(light)"', "icon": "'"$icon"'" }'
done
